/**
 * Comprehensive descriptions for all Cursor usage statistics
 * Organized by actual stat IDs from the backend
 */

export const STAT_DESCRIPTIONS = {
  // ==================== MESSAGE STATS ====================
  
  // Basic Counts
  'total_messages': 'Total number of messages exchanged between you and Cursor AI across all conversations',
  'user_messages': 'Number of messages you sent to Cursor AI (your prompts and questions)',
  'ai_messages': 'Number of responses generated by Cursor AI (including code suggestions and explanations)',
  'messages_per_session': 'Average number of messages exchanged per conversation session',
  'user_messages_per_session': 'Average number of user messages per session',
  'ai_messages_per_session': 'Average number of AI messages per session',
  
  // Message Types
  'chat_messages': 'Messages sent in chat mode (direct conversation)',
  'agent_mode_sessions': 'Sessions where agent mode was active (autonomous task completion)',
  'agentic_messages': 'Messages generated while Cursor was operating in autonomous agent mode',
  'composer_vs_tab_usage': 'Comparison of Composer mode vs Tab mode usage patterns',
  'chat_mode_sessions': 'Number of sessions conducted in chat mode',
  
  // Content Analysis
  'message_text_length': 'Average character count per message across all conversations',
  'messages_with_text': 'Number of messages containing text content',
  'messages_with_code_blocks': 'Number of messages containing markdown code blocks (```code```)',
  'code_blocks_generated': 'Total count of code blocks generated across all messages',
  'lines_of_code_in_blocks': 'Total lines of code within all code blocks',
  'code_block_languages': 'Distribution of programming languages used in code blocks',
  'files_referenced_in_code': 'Number of file references found within code blocks',
  'code_by_file': 'Distribution of code suggestions by file',
  'code_by_file_type': 'Distribution of code suggestions by file extension',
  'code_by_source': 'Source attribution for code suggestions (AI-generated vs user-modified)',
  
  // Thinking & Reasoning
  'messages_with_thinking': 'Number of AI responses that include visible reasoning/thinking process',
  'thinking_text_length': 'Average character count of the AI thinking/reasoning sections',
  'thinking_duration': 'Average time spent by AI in the thinking phase per message',
  'thinking_blocks_per_message': 'Average number of thinking blocks per message that includes thinking',
  
  // Tool Usage
  'messages_with_tools': 'Number of messages where Cursor invoked tools (file operations, searches, etc.)',
  'tool_invocations': 'Total number of tool invocations across all conversations',
  'unique_tool_types': 'Number of different tool types Cursor has used (read_file, search, edit, etc.)',
  'tools_per_message': 'Average number of tools used per message that contains tool calls',
  'most_used_tools': 'The tools that Cursor has invoked most frequently',
  'tool_usage_by_type': 'Breakdown of tool usage by tool type',
  'tool_success_rate': 'Percentage of tool calls that completed successfully',
  'tool_error_rate': 'Percentage of tool calls that resulted in errors',
  'tool_cancellation_rate': 'Percentage of tool calls that were cancelled before completion',
  'tool_status_distribution': 'Distribution of tool outcomes (success, error, cancelled)',
  'tool_success_failure': 'Comparison of successful vs failed tool invocations',
  'tool_arg_length': 'Average length of arguments passed to tools',
  'total_tool_invocations': 'Total count of all tool invocations',
  
  // Context & References
  'relevant_files': 'Files that were most relevant to conversations',
  'recently_viewed_files': 'Files you viewed recently during coding sessions',
  'unique_files_in_context': 'Number of unique files included as context across sessions',
  'docs_references': 'Number of references to external documentation',
  'web_references': 'Number of web URLs referenced in conversations',
  'messages_with_server_references': 'Messages containing server or API references',
  'web_searches_performed': 'Number of web searches Cursor performed',
  'messages_using_web': 'Messages that utilized web search capabilities',
  
  // Suggestions & Diffs
  'suggested_code_blocks': 'Number of code suggestions provided by Cursor',
  'accepted_suggestions': 'Number of suggestions you accepted and applied',
  'rejected_suggestions': 'Number of suggestions you rejected or ignored',
  'modified_suggestions': 'Number of suggestions you modified before accepting',
  'acceptance_rate': 'Percentage of suggestions accepted (accepted / total)',
  'suggestion_action_types': 'Breakdown of actions taken on suggestions (accept, reject, modify)',
  'assistant_suggested_diffs': 'Code diffs suggested by the AI assistant',
  'response_time_to_suggestions': 'Average time between suggestion and your response',
  'daily_acceptance_rate': 'Suggestion acceptance rate by day',
  'daily_suggested_lines_composer': 'Lines suggested per day in Composer mode',
  'daily_accepted_lines_composer': 'Lines accepted per day in Composer mode',
  'daily_suggested_lines_tab': 'Lines suggested per day in Tab mode',
  'daily_accepted_lines_tab': 'Lines accepted per day in Tab mode',
  
  // Tokens
  'total_tokens': 'Total tokens consumed (input + output) across all conversations',
  'input_tokens': 'Tokens used for your messages and context sent to AI',
  'output_tokens': 'Tokens used for AI-generated responses',
  'tokens_per_message': 'Average token count per message',
  'tokens_by_model': 'Token usage breakdown by AI model',
  'context_tokens_used': 'Tokens consumed for context (files, history, etc.)',
  'context_token_limit': 'Maximum context tokens allowed per session',
  'context_usage_percentage': 'Percentage of context token limit used',
  'sessions_near_context_limit': 'Sessions that approached or hit the context limit',
  
  // Models & Capabilities
  'model_usage_breakdown': 'Distribution of usage across different AI models',
  'model_switches': 'Number of times you switched between AI models',
  'sessions_by_model': 'Session count breakdown by model type',
  'messages_with_model_info': 'Messages containing model metadata',
  'sessions_with_capabilities': 'Sessions with special capabilities enabled (browser, file access)',
  'sessions_with_max_mode': 'Sessions using maximum capability mode',
  
  // Metadata & State
  'messages_with_checkpoints': 'Messages that created state checkpoints',
  'messages_with_diff_histories': 'Messages containing diff history',
  'messages_with_git_diffs': 'Messages including Git diff information',
  'messages_with_human_changes': 'Messages tracking manual code changes',
  'messages_with_console_logs': 'Messages containing console output',
  'messages_with_lints': 'Messages including linter error information',
  'message_timestamps': 'Distribution of message timestamps (activity patterns)',
  'time_between_messages': 'Average time gap between consecutive messages',
  
  // Activity Timing
  'peak_activity_hours': 'Hours of the day with highest message activity',
  'peak_activity_days': 'Days of the week with highest message activity',
  'active_days': 'Total number of days with at least one message',
  'inactive_days': 'Number of days since last activity',
  'activity_streak': 'Current streak of consecutive active days',
  'conversation_length': 'Average duration of conversation sessions',
  
  // Special Features
  'terminal_interactions': 'Number of terminal/command line interactions',
  'sessions_with_code_output': 'Sessions that generated executable code output',
  'refunded_messages': 'Messages that were refunded (due to errors or issues)',
  'nudge_messages': 'System nudge messages suggesting actions',
  
  // ==================== SESSION STATS ====================
  
  'total_sessions': 'Total number of distinct conversation sessions',
  'session_duration': 'Average time spent per conversation session',
  'named_sessions': 'Number of sessions with custom names',
  'session_name_keywords': 'Common keywords found in session names',
  'sessions_by_duration_bucket': 'Distribution of sessions by duration (short, medium, long)',
  'sessions_per_workspace': 'Number of sessions grouped by workspace/project',
  'diffs_per_session': 'Average number of code diffs per session',
  
  // File Operations
  'files_added': 'Total number of files created during sessions',
  'files_modified': 'Total number of files edited during sessions',
  'files_removed': 'Total number of files deleted during sessions',
  'most_modified_files': 'Files that have been edited most frequently',
  
  // ==================== CODE & DIFFS STATS ====================
  
  'code_diffs_total': 'Total number of code changes/diffs generated',
  'lines_added': 'Total lines of code added across all diffs',
  'lines_removed': 'Total lines of code deleted across all diffs',
  'lines_changed_per_diff': 'Average number of lines changed per diff',
  'net_lines': 'Net change in lines of code (additions - deletions)',
  'character_changes': 'Total character-level changes across diffs',
  'diff_line_spans': 'Distribution of diff sizes by line count',
  'edit_distance': 'Average edit distance (complexity) of changes',
  'similarity_ratio': 'Average similarity between old and new code versions',
  'tracked_code_lines': 'Total lines of code tracked for AI-assisted modifications',
  
  // ==================== DAILY USAGE STATS ====================
  
  // (These are temporal aggregations of the above stats)
  
  // ==================== CONTEXT STATS ====================
  
  // Linter Errors
  'contexts_with_linter_errors': 'Number of contexts that included linter error reports',
  'total_linter_errors': 'Total linter errors encountered across all contexts',
  'linter_errors': 'Current linter error count',
  'linter_errors_by_file_type': 'Distribution of linter errors by file extension',
  'linter_errors_by_source': 'Distribution of linter errors by source/rule',
  'files_with_linter_errors': 'Number of files with active linter errors',
  'errors_per_context': 'Average number of errors per context with errors',
  
  // TODOs
  'contexts_with_todos': 'Number of contexts that included TODO tracking data',
  'total_todos': 'Total number of TODO items tracked',
  'todos_by_status': 'Breakdown of TODOs by status (pending, in_progress, completed)',
  'todos_per_context': 'Average number of TODOs per context',
  
  // Git Context
  'contexts_with_git_changes': 'Number of contexts with uncommitted Git changes',
  'git_status_length': 'Average size of Git status information in context',
  
  // File Context
  'contexts_with_file_context': 'Number of contexts with attached file contents',
  'contexts_with_attached_chunks': 'Contexts with attached code chunks',
  'attached_code_chunks': 'Total code chunks attached as context',
  'attached_chunks_per_context': 'Average code chunks per context',
  'lines_in_attached_chunks': 'Total lines in attached code chunks',
  'codebase_context_chunks': 'Chunks from codebase search results',
  
  // Editor State
  'contexts_with_editor_state': 'Contexts that included editor state information',
  'contexts_with_current_file': 'Contexts with the current file included',
  'contexts_with_diffs': 'Contexts with code diff information',
  
  // User Ratios
  'user_ai_message_ratio': 'Ratio of user messages to AI messages',
}

/**
 * Get description for a stat ID
 * @param {string} statId - The stat identifier
 * @returns {string} Description or default message
 */
export function getStatDescription(statId) {
  return STAT_DESCRIPTIONS[statId] || `No description available for this statistic (${statId})`
}

/**
 * Check if a stat has a description
 * @param {string} statId - The stat identifier
 * @returns {boolean} True if description exists
 */
export function hasDescription(statId) {
  return statId in STAT_DESCRIPTIONS
}
